# Generated by Django 4.0 on 2022-01-05 10:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('DepartmentApp', '0001_initial'),
        ('FacultyApp', '0002_alter_faculty_department'),
    ]

    operations = [
        migrations.AlterField(
            model_name='faculty',
            name='department',
            field=models.ManyToManyField(to='DepartmentApp.Department'),
        ),
    ]
